package de.uniwue.jpp.mensabot.util;

import de.uniwue.jpp.mensabot.dataclasses.Meal;
import de.uniwue.jpp.mensabot.dataclasses.Menu;

import java.time.LocalDate;
import java.util.*;

//class used for local testing
public class MensabotUtil {
    public static Meal createSampleMeal() {
        return Meal.createMeal("Pizza Salami Schinken", 305);
    }

    public static List<Meal> createSampleMeals() {
       List<Meal> mealList = new ArrayList<>();
       mealList.add(Meal.createMeal("Pizza Salami Schinken", 305));
       mealList.add(Meal.createMeal("Premium Beef-Burger vom Simmentaler Rind mit Baerlauchremoulade und Schweizer Kaese", 485));
       mealList.add(Meal.createMeal("Falaffel auf orientalischem Gemuese und Bulgur", 255));
       mealList.add(Meal.createMeal("Geschmelzte Maultaschen mit Ei", 245));
       mealList.add(Meal.createMeal("Sommerlicher Salatteller mit Tomate und Mozzarella", 305));
       mealList.add(Meal.createMeal("Afrikanischer Erdnuss - Suesskartoffel \"Hot Pot\"", 205));
       mealList.add(Meal.createMeal("Veganer Burger \"Italian Style\" ", 330));
       mealList.add(Meal.createMeal("Pfannkuchen mit Apfel-Zimt-Topping", 205));
       mealList.add(Meal.createMeal("Gnocchi mit Kaesesoße & Tomatensugo", 255));
       mealList.add(Meal.createMeal("XXL-Schweineschnitzel paniert mit Zitrone", 370));
       return mealList;
    }

    public static Menu createSampleMenu() {
        Set<Meal> mealSet = new HashSet<>();
        mealSet.add(Meal.createMeal("Geschmelzte Maultaschen mit Ei", 245));
        mealSet.add(Meal.createMeal("Sommerlicher Salatteller mit Tomate und Mozzarella", 305));
        mealSet.add(Meal.createMeal("Veganer Burger \"Italian Style\" ", 330));
        mealSet.add(Meal.createMeal("XXL-Schweineschnitzel paniert mit Zitrone", 370));
        mealSet.add(Meal.createMeal("Pizza Salami Schinken", 305));
        mealSet.add(Meal.createMeal("Premium Beef-Burger vom Simmentaler Rind mit Baerlauchremoulade und Schweizer Kaese", 485));
        mealSet.add(Meal.createMeal("Falaffel auf orientalischem Gemuese und Bulgur", 255));
        mealSet.add(Meal.createMeal("Afrikanischer Erdnuss - Suesskartoffel \"Hot Pot\"", 205));
        mealSet.add(Meal.createMeal("Gnocchi mit Kaesesoße & Tomatensugo", 255));
        mealSet.add(Meal.createMeal("Pfannkuchen mit Apfel-Zimt-Topping", 205));
        return Menu.createMenu(LocalDate.of(2022,1,1), mealSet);
    }

    public static List<Menu> createSampleMenus() {
        List <Menu> menuList = new ArrayList<>();
        menuList.add(createSampleMenu());

        Set<Meal> mealSet1 = new HashSet<>();
        mealSet1.add(Meal.createMeal("Pizza Salami Schinken", 305));
        mealSet1.add(Meal.createMeal("Premium Beef-Burger vom Simmentaler Rind mit Baerlauchremoulade und Schweizer Kaese", 485));
        mealSet1.add(Meal.createMeal("Falaffel auf orientalischem Gemuese und Bulgur", 255));
        menuList.add(Menu.createMenu(LocalDate.of(2022,1,2), mealSet1));

        Set<Meal> mealSet2 = new HashSet<>();
        mealSet2.add(Meal.createMeal("Geschmelzte Maultaschen mit Ei", 245));
        mealSet2.add(Meal.createMeal("Sommerlicher Salatteller mit Tomate und Mozzarella", 305));
        mealSet2.add(Meal.createMeal("Afrikanischer Erdnuss - Suesskartoffel \"Hot Pot\"", 205));
        menuList.add(Menu.createMenu(LocalDate.of(2022,1,3), mealSet2));

        Set<Meal> mealSet3 = new HashSet<>();
        mealSet3.add(Meal.createMeal("Veganer Burger \"Italian Style\" ", 330));
        mealSet3.add(Meal.createMeal("Gnocchi mit Kaesesoße & Tomatensugo", 255));
        mealSet3.add(Meal.createMeal("Pfannkuchen mit Apfel-Zimt-Topping", 205));
        menuList.add(Menu.createMenu(LocalDate.of(2022,1,4), mealSet3));

        Set<Meal> mealSet4 = new HashSet<>();
        mealSet4.add(Meal.createMeal("Geschmelzte Maultaschen mit Ei", 245));
        mealSet4.add(Meal.createMeal("Sommerlicher Salatteller mit Tomate und Mozzarella", 305));
        mealSet4.add(Meal.createMeal("Pizza Salami Schinken", 305));
        mealSet4.add(Meal.createMeal("Premium Beef-Burger vom Simmentaler Rind mit Baerlauchremoulade und Schweizer Kaese", 485));
        mealSet4.add(Meal.createMeal("Falaffel auf orientalischem Gemuese und Bulgur", 255));
        menuList.add(Menu.createMenu(LocalDate.of(2022,1,5), mealSet4));
        return menuList;
    }

    public static Set<Meal> createRandomMealSet(){
        List<Meal> mealList = createMoreSampleMeals();
        Set<Meal> mealSet = new HashSet<>();
        int indexToGet;
        Random ran = new Random();
        int menuSize = ran.nextInt(6);

        for(int i = 0; i <= menuSize; i++){
            indexToGet = ran.nextInt(mealList.size());
            mealSet.add(mealList.get(indexToGet));
        }
        return mealSet;
    }

    public static List<Meal> createMoreSampleMeals() {
        List<Meal> mealList = new ArrayList<>();
        mealList.add(Meal.createMeal("Mensa-Vital: Fruchtige Vollkornreis-Gemüsepfanne mit Tomatensoße", 210));
        mealList.add(Meal.createMeal("Kokos - Gemüsecurry \"Thai - Style\"", 235));
        mealList.add(Meal.createMeal("Spaghetti mit Soja - Pastaschuta", 260));
        mealList.add(Meal.createMeal("Veganer Quinoa - Chili - Burger", 380));
        mealList.add(Meal.createMeal("Mensa-Vital: Bohnen - Zucchini - Chili mit Vollkornreis", 210));
        mealList.add(Meal.createMeal("Mensa-Vital: Gemüse - Reispfanne mit Kernmix", 280));
        mealList.add(Meal.createMeal("Green Wraps mit Guacamole, Walnüssen und Salat", 435));
        mealList.add(Meal.createMeal("Hähnchen Cordon bleu", 310));
        mealList.add(Meal.createMeal("Veganer Chipotle Burrito", 310));
        mealList.add(Meal.createMeal("Kokos - Gemüsecurry \"Thai - Style\" , mit Basmatireis", 280));
        mealList.add(Meal.createMeal("Veganer Chipotle Burrito", 280));
        mealList.add(Meal.createMeal("Mensa-Vital: Schupfnudel-Pfanne mit Gemüse und Champignons", 335));
        mealList.add(Meal.createMeal("Afrikanischer Erdnuss - Süßkartoffel \"Hot Pot\"", 335));
        mealList.add(Meal.createMeal("Siebenschwabenplatte", 380));
        mealList.add(Meal.createMeal("Geflügelhacksteak auf Champignonsoße", 260));
        mealList.add(Meal.createMeal("Mensa-Vital: Kichererbsen - Gemüse - Curry mit Basmatireis", 260));
        mealList.add(Meal.createMeal("Chicken Nuggets \"Honey - B.B.Q.\"", 445));
        mealList.add(Meal.createMeal("Ofenfrisches Schweineschäufele mit Soße", 475));
        mealList.add(Meal.createMeal("Gnocchi \"Caprese\"", 335));
        mealList.add(Meal.createMeal("Köttbullar mit Zitronen - Pfeffersoße", 280));
        mealList.add(Meal.createMeal("Vegane Gemüsemaultaschen mit Tomatensoße und veganem Käse", 310));
        mealList.add(Meal.createMeal("Mensa-Vital: Seelachsfilet auf feurigem Gemüsecurry und Ingwerreis", 410));
        mealList.add(Meal.createMeal("Gnocchi an Tomatensugo mit Parmesan.", 280));
        mealList.add(Meal.createMeal("Asiatisches Hähnchen - Gemüseragout mit Mienudeln", 380));
        mealList.add(Meal.createMeal("Mensa-Vital: Kartoffel-Linseneintopf mit Koriander und Vollkornbrot", 335));
        mealList.add(Meal.createMeal("Hacksteak mit Bratensoße", 210));
        mealList.add(Meal.createMeal("Schneller Teller: Schweinegeschnetzeltes in Kräuterrahm mit Spätzle, Erbsen und Möhren", 320));
        mealList.add(Meal.createMeal("Süßkartoffel - Rucolaschnitte an Balkansoße", 280));
        mealList.add(Meal.createMeal("Hähnchen Cordon bleu", 335));
        mealList.add(Meal.createMeal("Ofenfrische Entenkeule an Orangensoße", 410));
        mealList.add(Meal.createMeal("Flammkuchen mit Räucherlachs", 485));
        mealList.add(Meal.createMeal("Seelachsfilet gebacken mit hausgemachtem Kräuterdip", 310));
        mealList.add(Meal.createMeal("Gnocchi \"Caprese\"", 365));
        mealList.add(Meal.createMeal("Mensa-Vital: Curry - Gemüsetopf mit Pute und Vollkornreis", 410));
        mealList.add(Meal.createMeal("Mensa-Vital: Vollkornspaghetti mit Bolognese von roten Linsen", 210));
        mealList.add(Meal.createMeal("Mensa-Vital: Vollkornspaghetti mit Ragout von roten Linsen", 210));
        mealList.add(Meal.createMeal("Geflügelhacksteak auf Champignonsoße", 235));
        mealList.add(Meal.createMeal("Entenragout in Orangensoße", 380));
        mealList.add(Meal.createMeal("Spaghetti \"Bolognese\"", 435));
        mealList.add(Meal.createMeal("Käsespätzle mit Röstzwiebeln", 310));
        mealList.add(Meal.createMeal("Wrap \"Griechische Art\"", 310));
        mealList.add(Meal.createMeal("Afrikanischer Erdnuss - Süßkartoffel \"Hot Pot\"", 280));
        mealList.add(Meal.createMeal("Germknödel mit Sauerkirschfüllung auf Vanillesoße", 210));
        mealList.add(Meal.createMeal("Veganer Süßkartoffel - Rösti - Burger", 380));
        mealList.add(Meal.createMeal("Vegane Gemüsemaultaschen mit Tomatensoße", 280));
        mealList.add(Meal.createMeal("Ofenfrischer Schweinekammbraten in Biersoße", 310));
        mealList.add(Meal.createMeal("Gnocchi \"Caprese\"", 280));
        mealList.add(Meal.createMeal("Pasta mit Soja - Pastaschuta", 235));
        mealList.add(Meal.createMeal("Pizza \"Melanzane\"", 410));
        mealList.add(Meal.createMeal("Kartoffelgnocchi - Gemüsepfanne mit Sahnesoße", 280));
        mealList.add(Meal.createMeal("Gebratenes Asiagemüse mit Basmatireis", 280));
        mealList.add(Meal.createMeal("Mensa-Vital: Kartoffel-Erbseneintopf mit Koriander, Minze und Vollkornbrot", 335));
        mealList.add(Meal.createMeal("Mensa-Vital: Kichererbsen - Gemüse - Curry mit Basmatireis", 210));
        mealList.add(Meal.createMeal("Hähnchenbrustfilet mit Paprikarahmsoße", 435));
        mealList.add(Meal.createMeal("Mensa-Vital: Hähnchenbrust in Rucola -Pestosoße mit Bandnudeln", 365));
        mealList.add(Meal.createMeal("Mensa-Vital: Gnocchis mit buntem Gemüse", 310));
        mealList.add(Meal.createMeal("Veganer Indischer Hotpot \"Tandoori Style\"", 210));
        mealList.add(Meal.createMeal("Veganer Burger mit Brokkoli - Nussecke", 380));
        mealList.add(Meal.createMeal("Kokos - Gemüsecurry \"Thai - Style\" mit Reis", 280));
        mealList.add(Meal.createMeal("Spaghetti \"Bolognese\"", 410));
        mealList.add(Meal.createMeal("Schneller Teller: Vegane Gemüsemaultaschen mit geschmelzten Zwiebeln und Salat", 320));
        mealList.add(Meal.createMeal("XXL-Schweineschnitzel paniert mit Zitrone", 410));
        mealList.add(Meal.createMeal("Seelachsfilet gebacken mit Krabbendip", 365));
        mealList.add(Meal.createMeal("Mensa-Vital: Bohnen-Gemüse-Ragout mit Sojasprossen, Erdnüssen und Kräuterkartoffeln", 235));
        mealList.add(Meal.createMeal("Spätzle mit Käsesoße und Gemüse", 310));
        mealList.add(Meal.createMeal("Schneller Teller: Gemüsebratling mit Gitterkartoffeln, Salsadip und feurigem Bohnensalat", 320));
        mealList.add(Meal.createMeal("Veganer Burger \"Italian Style\"", 310));
        mealList.add(Meal.createMeal("Milchreis mit Waldbeeren", 280));
        mealList.add(Meal.createMeal("Mensa-Vital: Pennenudeln mit Favabohnen, Paprika und Sonnenblumenkerne", 235));
        mealList.add(Meal.createMeal("Hähnchenbrustfilet mit Kürbispanade", 280));
        mealList.add(Meal.createMeal("Veganer Riesenrösti \"Italia\"", 335));
        mealList.add(Meal.createMeal("Schneller Teller: Falafelbällchen auf Gemüse und Couscous", 320));
        mealList.add(Meal.createMeal("Mensa-Vital: Scharfes Kürbisgemüse mit Linsen,Tofu und Rucola auf Penne Rigate", 210));
        mealList.add(Meal.createMeal("Gnocchi \"Caprese\"", 310));
        mealList.add(Meal.createMeal("Maultaschen mit Tomatensoße", 280));
        mealList.add(Meal.createMeal("Mensa-Vital: Gemüse Couscous-Pfanne mit veganem Joghurt-Ingwer-Dip", 235));
        mealList.add(Meal.createMeal("Tortellini mit Tomatensoße", 280));
        mealList.add(Meal.createMeal("Cannelloni \"Ricotta\" weißer Soße", 280));
        mealList.add(Meal.createMeal("Hähnchenpiccata an Tomatenragout", 310));
        mealList.add(Meal.createMeal("Gnocchi mit Käsesoße & Tomatensugo", 310));
        mealList.add(Meal.createMeal("Pita mit Gyros - Kichererbsen und Haferjoghurt - Soße", 310));
        mealList.add(Meal.createMeal("Süßkartoffel \"Hot Pot\" mit Tofu", 335));
        mealList.add(Meal.createMeal("Spaghetti \"Bolognese\"", 380));
        mealList.add(Meal.createMeal("Schweinerückensteak mit Paprikarahmsoße", 310));
        mealList.add(Meal.createMeal("Tortelloni \"Tricolore\" an Sahnesoße mit Tomatenwürfel", 310));
        mealList.add(Meal.createMeal("Köttbullar mit Rahmsoße", 280));
        mealList.add(Meal.createMeal("Hähnchenbrustfilet mit Kürbispanade", 310));
        mealList.add(Meal.createMeal("Geflügelhacksteak mit Geflügelrahmsoße", 260));
        mealList.add(Meal.createMeal("Tortelloni \"Tricolore\" an Pestosoße", 310));
        mealList.add(Meal.createMeal("Tortelli Ricotta & Spinaci mit Gemüserahmsoße", 335));
        mealList.add(Meal.createMeal("Flammkuchen \"Klassisch\"", 310));
        mealList.add(Meal.createMeal("Gebratene Ente\"süß-sauer\" mit Wokgemüse", 475));
        mealList.add(Meal.createMeal("Mensa-Vital: Asiatische Gemüsepfanne mit Tofu und Glasnudeln", 280));
        mealList.add(Meal.createMeal("Käsespätzle mit Röstzwiebeln", 335));
        mealList.add(Meal.createMeal("Bennos Zentimeterpfanne", 310));
        mealList.add(Meal.createMeal("Hähnchenpiccata an Tomatenragout", 335));
        mealList.add(Meal.createMeal("Tortelloni \"Tricolore\" an Sahnesoße mit Tomatenwürfel", 335));
        mealList.add(Meal.createMeal("2 Stück Hähnchenschnitzel \"Wiener Art\"", 310));
        mealList.add(Meal.createMeal("Penne \"Arrabbiata\" - Vegan möglich", 210));
        mealList.add(Meal.createMeal("Pizza \"Napoli\"", 365));
        mealList.add(Meal.createMeal("Köttbullar mit Rahmsoße", 310));
        mealList.add(Meal.createMeal("Gefüllte vegane Paprikaschote mit Tomatensoße", 260));
        mealList.add(Meal.createMeal("Hähnchenbrustfilet an Zitronen- Pfeffersoße", 310));
        mealList.add(Meal.createMeal("Backfischhappen mit hausgemachtem Tomaten Olivendip", 310));
        mealList.add(Meal.createMeal("Paniertes Schweineschnitzel", 310));
        mealList.add(Meal.createMeal("Mensa-Vital: Gemüsepaella mit Vollkornreis und Walnüssen", 280));
        mealList.add(Meal.createMeal("Spaghetti \"Caprese\"", 310));
        mealList.add(Meal.createMeal("Chicken Nuggets \"Honey - B.B.Q.\"", 280));
        mealList.add(Meal.createMeal("Vegane Bulgurpfanne mit Gemüse und orientalischem Tomatenragout", 235));
        mealList.add(Meal.createMeal("Gebackene Kartoffeltaschen \"Kräuterfrischkäse\"", 280));
        mealList.add(Meal.createMeal("Dampfkartoffeln hausgemachtem Schnittlauchquark", 280));
        mealList.add(Meal.createMeal("Milchreis mit Rotweinzwetschgen", 260));
        mealList.add(Meal.createMeal("Chicken Nuggets \"Honey - B.B.Q.\"", 365));
        mealList.add(Meal.createMeal("Pizza \"Funghi\"", 365));
        mealList.add(Meal.createMeal("Burger \"Italiana\" mit Tomate, Rucola und Pesto", 485));
        mealList.add(Meal.createMeal("Wrap - Oriental mit Falafel und pikantem Hummus", 365));
        mealList.add(Meal.createMeal("Mensa-Vital: Süßkartoffelcurry mit Kichererbsen Basmatireis", 380));
        mealList.add(Meal.createMeal("Vegane Rote - Bete - Puffer Pastinaken - Karottengemüse", 310));
        mealList.add(Meal.createMeal("Süßkartoffel - Burger mit Guacamole", 410));
        mealList.add(Meal.createMeal("Gebackene Kartoffeltaschen \"Mozzarella\"", 260));
        mealList.add(Meal.createMeal("Gebratener Reis mit Asiagemüse", 280));
        mealList.add(Meal.createMeal("Kokos - Gemüsecurry \"Thai - Style\"", 280));
        mealList.add(Meal.createMeal("Schweinerückensteak mit Rahmsoße", 365));
        mealList.add(Meal.createMeal("Gebackenes Schollenfilet mit hausgemachtem Kräuterdip", 365));
        mealList.add(Meal.createMeal("Matjesfilet \"Hausfrauen Art\"", 335));
        mealList.add(Meal.createMeal("Fish´n Chips", 410));
        mealList.add(Meal.createMeal("Calamaris mit Salsa - Joghurt - Dip", 310));
        mealList.add(Meal.createMeal("Mensa-Vital: Fruchtige Vollkornreis-  Gemüsepfanne mit Tomatensoße", 210));
        mealList.add(Meal.createMeal("Hähnchenbrustfilet an Glühweinsoße", 310));
        mealList.add(Meal.createMeal("Mensa-Vital: Bohnen-Gemüse-Ragout mit Sojasprossen, Walnüssen und Kräuterkartoffeln", 280));
        mealList.add(Meal.createMeal("Wrap mit mediterraner Gemüsefüllung & veganem Kräuterdip", 280));
        mealList.add(Meal.createMeal("Vital: Pasta mit veganem Gemüseragout", 235));
        mealList.add(Meal.createMeal("Hamburger", 445));
        mealList.add(Meal.createMeal("Gebratener Reis mit Asiagemüse", 260));
        mealList.add(Meal.createMeal("Chili - Cheese - Burger", 445));
        mealList.add(Meal.createMeal("Mensa-Vital: Tofusteak auf Buchweizen-Champignon-Pfanne mit Schnittlauchdip", 280));
        mealList.add(Meal.createMeal("Vegane Gemüsemaultaschen an Tomatensoße", 280));
        mealList.add(Meal.createMeal("Bacon Burger Royal", 445));
        mealList.add(Meal.createMeal("Rinderhacksteak an Cognac - Pfeffersoße", 280));
        mealList.add(Meal.createMeal("Fränkisches Geröstel", 335));
        mealList.add(Meal.createMeal("Dampfkartoffeln hausgemachtem Schnittlauchquark", 260));
        mealList.add(Meal.createMeal("Mensa-Vital: Rindergulasch mit Champignons, Blattsalat und Kroketten", 435));
        mealList.add(Meal.createMeal("Sojaragout mit Pennini - Nudeln & veganem Käse", 235));
        mealList.add(Meal.createMeal("Tortelloni \"Tricolore\" an Sahnesoße mit Tomatenwürfel", 280));
        mealList.add(Meal.createMeal("Tortellini \"Formaggio\" an Pestosoße", 335));
        mealList.add(Meal.createMeal("Dampfkartoffeln mit hausgemachten veganem Kräuter- Haferdip", 280));
        mealList.add(Meal.createMeal("Pizza \"Speciale\"", 435));
        mealList.add(Meal.createMeal("Vegane Tortellini mit veganer Kräutersoße", 310));
        mealList.add(Meal.createMeal("Schweinenackensteak vom Grill mit Waldpilzsoße \"Jäger Art\"", 335));
        mealList.add(Meal.createMeal("Fleischbällchen mit Curry-Ketchupsoße", 310));
        mealList.add(Meal.createMeal("Burger \"Italiana\" mit Tomate, Rucola und Pesto", 435));
        mealList.add(Meal.createMeal("Kartoffelgnocchi an Tomatenrahmsoße", 280));
        mealList.add(Meal.createMeal("Calamaris mit Limetten - Joghurtdip", 335));
        mealList.add(Meal.createMeal("Hamburger", 410));
        mealList.add(Meal.createMeal("Pizza \"Spinat & Hirtenkäse\"", 410));
        mealList.add(Meal.createMeal("Pizza \"Funghi\"", 380));
        mealList.add(Meal.createMeal("Schneller Teller: Schwäbischer Linseneintopf mit Spätzle und ein Paar Wiener", 320));
        mealList.add(Meal.createMeal("Rinderschmorbraten mit Madeirasoße", 445));
        mealList.add(Meal.createMeal("Vegane Pita gefüllt mit Sojagyros und Gemüse", 380));
        mealList.add(Meal.createMeal("Hacksteak Braune Grundsoße / Demi Glace", 210));
        mealList.add(Meal.createMeal("Mensa-Vital: Schupfnudel-Pfanne mit Gemüse und Pilzen", 335));
        mealList.add(Meal.createMeal("Lasagne al Forno", 380));
        mealList.add(Meal.createMeal("Mensa-Vital: Feuriger Curry - Gemüsetopf mit Pute und Reis", 380));
        mealList.add(Meal.createMeal("Chili con Carne", 435));
        mealList.add(Meal.createMeal("Sojaragout mit Pennini - Nudeln", 280));
        mealList.add(Meal.createMeal("Schnitzelburger", 445));
        mealList.add(Meal.createMeal("Mensa-Vital: Süßkartoffelcurry mit Kichererbsen und Basmatireis", 380));
        mealList.add(Meal.createMeal("Tortelloni \"Tricolore\" an Tomatenrahmsoße", 310));
        mealList.add(Meal.createMeal("Mensa-Vital: Kürbisgemüse mit Linsen und Rucola auf Wildreis", 210));
        mealList.add(Meal.createMeal("Mensa-Vital: Scharfes Kürbisgemüse mit Linsen und Cashewkernen auf Pasta", 210));
        mealList.add(Meal.createMeal("Mensa-Vital: Süßkartoffelcurry mit Kichererbsen , Zucchini und Basmatireis", 380));
        mealList.add(Meal.createMeal("Calamaris mit Zitronen-Mayo", 280));
        mealList.add(Meal.createMeal("Mensa-Vital: Asiatische Gemüsepfanne mit Glasnudeln", 280));
        mealList.add(Meal.createMeal("Pizza \"Margherita\"", 335));
        mealList.add(Meal.createMeal("Fisch Burger", 445));
        mealList.add(Meal.createMeal("Crinkle Wedges mit Mayo - Dip", 260));
        mealList.add(Meal.createMeal("Mensa-Vital: Hähnchenbrust in Rucolasoße mit Bandnudeln", 365));
        mealList.add(Meal.createMeal("Countrykartoffeln mit hausgemachtem Avocado Chili Dip", 280));
        mealList.add(Meal.createMeal("Rinderhacksteak an Pfefferrahmsoße", 280));
        mealList.add(Meal.createMeal("Feuerspieß an Paprikasoße", 335));
        mealList.add(Meal.createMeal("Riesenrösti \"Italia\"", 365));
        mealList.add(Meal.createMeal("Mensa-Vital: Bunte Farfalle mit Feldsalatpesto und Cherrytomaten, dazu Möhrenrohkost mit Sesam", 310));
        mealList.add(Meal.createMeal("Lasagne al Forno", 410));
        mealList.add(Meal.createMeal("Tortelloni \"Tricolore\" mit Sahnesoße", 280));
        mealList.add(Meal.createMeal("Mensa-Vital: Kichererbsen - Kokos - Korma mit Mandelreis", 235));
        mealList.add(Meal.createMeal("Milchreis mit Sauerkirschen", 260));
        mealList.add(Meal.createMeal("Tortelloni \"Tricolore\" mit Tomatensoße und Gouda", 310));
        mealList.add(Meal.createMeal("Mensa-Vital: Gemüse Couscous-Pfanne mit Joghurt-Ingwer-Dip", 235));
        mealList.add(Meal.createMeal("Mensa-Vital: Putengeschnetzeltes \"Thailändische Art\" mit Duftreis", 335));
        mealList.add(Meal.createMeal("Vegane Gemüsetortellini mit veganer Kräutersoße", 310));
        mealList.add(Meal.createMeal("Fish´n Chips", 380));
        mealList.add(Meal.createMeal("Veganes Chili sin carne \"Texas Style\"", 235));
        mealList.add(Meal.createMeal("Wrap - Oriental mit Falafel und pikantem Hummus", 380));
        mealList.add(Meal.createMeal("Mensa-Vital: Tofusteak auf Buchweizen - Champignon-Pfanne mit Paprikadip", 280));
        mealList.add(Meal.createMeal("Mensa-Vital: Feuriges Gemüse-Rindfleisch-Curry mit Nudeln", 435));
        mealList.add(Meal.createMeal("\"Fajita Mexicana\"", 435));
        mealList.add(Meal.createMeal("Mensa-Vital: Bohnen-Gemüse-Ragout mit Gemüse, Erdnüssen und Kräuterkartoffeln", 235));
        mealList.add(Meal.createMeal("Seelachsfilet gebacken mit Remouladensoße", 365));
        mealList.add(Meal.createMeal("Marokkanischer Gemüseeintopf mit Kichererbsen und Ofenkartoffeln", 235));
        mealList.add(Meal.createMeal("Veganes Linsen - Curry - Dal mit Karotten und Ingwer", 260));
        mealList.add(Meal.createMeal("Sojaragout mit Pennini - Nudeln", 235));
        mealList.add(Meal.createMeal("Lasagne al Forno", 445));
        mealList.add(Meal.createMeal("Hähnchenschnitzel im Knuspermantel", 310));
        mealList.add(Meal.createMeal("Hacksteak mit Kürbisragout", 260));
        mealList.add(Meal.createMeal("Lasagne al Forno", 435));
        mealList.add(Meal.createMeal("Pizza \"Spinat & Hirtenkäse\"", 310));
        mealList.add(Meal.createMeal("Mensa-Vital: Kichererbsen - Kokos - Korma mit Mandelreis", 260));
        mealList.add(Meal.createMeal("Hacksteak an Cognac - Pfeffersoße", 280));
        mealList.add(Meal.createMeal("Mensa-Vital: Limettenspaghetti mit Erbsen - Pilz - Ragout", 235));
        mealList.add(Meal.createMeal("Fish´n Chips", 280));
        mealList.add(Meal.createMeal("Mensa-Vital: Dampfkartoffeln mit Kräuterdip und Currygemüse", 235));
        mealList.add(Meal.createMeal("Gebackenes Schollenfilet mit Remouladensoße", 365));
        mealList.add(Meal.createMeal("Gemüsemaultaschen in Karotten Ingwersoße", 280));
        mealList.add(Meal.createMeal("Semmelknödel auf Champignonrahmsoße", 280));
        mealList.add(Meal.createMeal("Sojaragout mit Pennini - Nudeln", 260));
        mealList.add(Meal.createMeal("Schweinerückensteak \"Berner Art\"", 310));
        mealList.add(Meal.createMeal("Pizza \"Melanzane\" mit gegrillter Aubergine, Mozzarella und Pesto", 410));
        mealList.add(Meal.createMeal("Currywurst", 310));
        mealList.add(Meal.createMeal("Tortellini in Sahnesoße al Forno", 280));
        mealList.add(Meal.createMeal("Falafelbällchen auf Couscous Gemüse", 310));
        mealList.add(Meal.createMeal("Falafelbällchen auf Couscous Gemüse", 280));
        mealList.add(Meal.createMeal("Vegetarischer \"Halloumi-Burger\" mit Paprikarelish", 410));
        mealList.add(Meal.createMeal("Mensa-Vital: Bunte Paprikapfanne mit Ingwer und Bambus dazu Zartweizen", 335));
        mealList.add(Meal.createMeal("Hähnchenbrustfilet auf Champignonrahmsoße", 310));
        mealList.add(Meal.createMeal("Vital: Kartoffel-Erbseneintopf mit Koriander, und Vollkornbrot", 335));
        mealList.add(Meal.createMeal("Süßkartoffel - Rucolaschnitte mit veganer Kräutersoße", 260));
        mealList.add(Meal.createMeal("Countrykartoffeln mit Sweet - Chili Joghurt - Dip", 210));
        mealList.add(Meal.createMeal("Seelachsfilet gebacken mit Remouladensoße", 380));
        mealList.add(Meal.createMeal("Tortellini \"Formaggio\"", 310));
        mealList.add(Meal.createMeal("Wrap \"Italiana\"", 280));
        mealList.add(Meal.createMeal("Schweinegeschnetzeltes in Paprikarahm", 310));
        mealList.add(Meal.createMeal("Veganer Kartoffel - Kürbisauflauf", 310));
        mealList.add(Meal.createMeal("Mensa-Vital: Bohnen - Zucchini - Chili mit Couscous", 210));
        mealList.add(Meal.createMeal("Mensa-Vital: Kabeljaufilet auf Blattspinat mit Tagliatelle", 445));
        mealList.add(Meal.createMeal("Louisiana Gumbo", 280));
        mealList.add(Meal.createMeal("Pita mit Gyros - Kichererbsen und Sojajoghurt - Soße", 335));
        mealList.add(Meal.createMeal("Crinkle Wedges mit Sweet - Chili - Dip", 260));
        mealList.add(Meal.createMeal("Griechische Gyrospfanne", 380));
        mealList.add(Meal.createMeal("Mensa-Vital: Geschnetzeltes mit grünem Pfeffer, Brokkoli, gerösteten Mandeln und Spätzle", 310));
        mealList.add(Meal.createMeal("Flammkuchen mit Landschinken und Rucola", 445));
        mealList.add(Meal.createMeal("Hähnchenbrustfilet an Rosmarinsoße", 410));
        mealList.add(Meal.createMeal("Gebackene Kartoffelspiralen mit Salsadip", 280));
        mealList.add(Meal.createMeal("Veganes Red Massaman-Curry", 235));
        mealList.add(Meal.createMeal("Kartoffelspiralen mit Tomatensalsa", 260));
        mealList.add(Meal.createMeal("Schweinegeschnetzeltes in Kräuterrahm", 335));
        mealList.add(Meal.createMeal("Mensa-Vital: Ofenkartoffeln mit Kräuterdip und Currygemüse", 235));
        mealList.add(Meal.createMeal("Wrap \"Italiana\"", 310));
        mealList.add(Meal.createMeal("Schweinenackensteak vom Grill mit Kräuterbutter", 310));
        mealList.add(Meal.createMeal("Sauerbraten \"Christkindl Art\" mit Lebkuchensoße", 435));
        mealList.add(Meal.createMeal("-", 365));
        mealList.add(Meal.createMeal("Mensa-Vital: Linsen-Kartoffel-Kokos-Pfanne, dazu einen Blattsalat mit Himbeervinaigrette", 235));
        mealList.add(Meal.createMeal("Schweinerückensteak an Pfefferrahmsoße", 335));
        mealList.add(Meal.createMeal("Vegane Lasagne", 435));
        mealList.add(Meal.createMeal("Kaiserschmarrn mit Apfelmus", 260));
        mealList.add(Meal.createMeal("Gemüsebratling mit Salsadip und Salatbouquet", 280));
        mealList.add(Meal.createMeal("Hirschgulasch in Pilzsoße", 380));
        mealList.add(Meal.createMeal("Kokos - Gemüsecurry \"Thai - Style\" mit Basmatireis", 280));
        mealList.add(Meal.createMeal("Kaiserschmarrn mit Apfelmus", 280));
        mealList.add(Meal.createMeal("Vegane Lasagne", 445));
        mealList.add(Meal.createMeal("Backfischhappen mit Tatarensoße", 310));
        mealList.add(Meal.createMeal("Mensa-Vital: Linsen-Kartoffel-Kokos-Pfanne, dazu einen Blattsalat mit Himbeervinaigrette", 260));
        mealList.add(Meal.createMeal("Mensa-Vital: Seelachs \"Provenciale\" auf grünen Bandnudeln", 410));
        mealList.add(Meal.createMeal("Lachsnudeln mit Lauchstreifen in feiner Sahnesoße", 445));
        mealList.add(Meal.createMeal("Kartoffelgnocchi - Gemüsepfanne mit Sahnesoße", 310));
        mealList.add(Meal.createMeal("Pizza \"Schinken\"", 365));
        mealList.add(Meal.createMeal("Mensa-Vital: Süßkartoffelcurry mit Kichererbsen, Gemüsestreifen und Basmatireis", 380));
        mealList.add(Meal.createMeal("Buntbarschfilet auf Karotten - Kokossoße, mit Duftreis", 380));
        mealList.add(Meal.createMeal("Mensa-Vital: Bunte Paprikapfanne mit Ingwer und Bambus dazu Zartweizen", 260));
        mealList.add(Meal.createMeal("Apfelstrudel \"Tiroler Art\" mit Vanillesoße", 280));
        mealList.add(Meal.createMeal("Schweinerückensteak an Pfefferrahmsoße", 365));
        mealList.add(Meal.createMeal("Schweinerückensteak auf Champignonsoße", 365));
        mealList.add(Meal.createMeal("Ofenfrischer Krustenbraten mit Soße", 310));
        mealList.add(Meal.createMeal("Schupfnudel - Gemüsepfanne", 335));
        mealList.add(Meal.createMeal("Pizza Vegetale - mit Grillgemüse", 435));
        mealList.add(Meal.createMeal("Mensa-Vital: Feuriger Curry - Gemüsetopf mit Pute und Vollkornreis", 380));
        mealList.add(Meal.createMeal("Cannelloni \"Ricotta\"", 380));
        mealList.add(Meal.createMeal("Mensa-Vital: Scharfes Kürbisgemüse mit Linsen und Rucola auf Penne Rigate", 210));
        mealList.add(Meal.createMeal("Hähnchenbrustfilet mit Soße Hollandaise & Brokkoli", 310));
        mealList.add(Meal.createMeal("Cheese Burger", 445));
        mealList.add(Meal.createMeal("Ein Paar Bratwürste Sauerkraut", 280));
        mealList.add(Meal.createMeal("Pulled Pork Burger mit Coleslaw", 410));
        mealList.add(Meal.createMeal("Vegane Pizza \"Margherita\"", 380));
        mealList.add(Meal.createMeal("Countrykartoffeln mit Sweet - Chili - Dip", 235));
        mealList.add(Meal.createMeal("Countrykartoffeln mit Salsadip", 280));
        mealList.add(Meal.createMeal("Paniertes Putenschnitzel", 310));
        mealList.add(Meal.createMeal("Hähnchenfiletspieß auf Champignonrahmsoße", 365));
        mealList.add(Meal.createMeal("Hähnchen Cordon bleu", 365));
        mealList.add(Meal.createMeal("Vegane Lasagne", 410));
        mealList.add(Meal.createMeal("Green Wraps mit Guacamole, Walnüssen und Salat", 410));
        mealList.add(Meal.createMeal("Mensa-Vital: Ofenkartoffeln mit Kräuterdip und Meditteranem Gemüse", 280));
        mealList.add(Meal.createMeal("Vegane Pita gefüllt mit Sojagyros und Salat", 335));
        mealList.add(Meal.createMeal("Knusperschnitzel vom Schwein", 310));
        mealList.add(Meal.createMeal("Gebackenes Schollenfilet mit Mayo - Dip und Blattsalat", 380));
        mealList.add(Meal.createMeal("Mensa-Vital: Ofenkartoffeln mit Kräuterdip und Currygemüse", 280));
        mealList.add(Meal.createMeal("Bunte Kartoffelgnocchi - Gemüsepfanne mit Sahnesoße", 280));
        mealList.add(Meal.createMeal("Schupfnudel - Gemüsepfanne", 380));
        mealList.add(Meal.createMeal("Mensa-Vital: Tagliatelle mit Lauch-Soja-Soße und gehackten Walnüssen", 310));
        mealList.add(Meal.createMeal("Gyros mit hausgemachtem Tsatsiki", 380));
        mealList.add(Meal.createMeal("Mensa-Vital: Chili sin Carne mit Kräuterreis", 210));
        mealList.add(Meal.createMeal("Geflügelhacksteak mit Rahmsoße", 280));
        mealList.add(Meal.createMeal("Fischpfanne \"Asia\" mit Nudeln", 410));
        mealList.add(Meal.createMeal("Mensa-Vital: Bunte Farfalle mit Feldsalatpesto und Cherrytomaten, dazu Möhrenrohkost mit Sesam", 365));
        mealList.add(Meal.createMeal("Gyros mit hausgemachtem Tsatsiki", 365));
        return mealList;
    }

}